from __future__ import annotations

from pathlib import Path

from code_rag.models import FileClass, path_language
from code_rag.settings import Settings


VENDOR_DIRS = {
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "vendor",
    "target",
    "build",
    "dist",
    "coverage",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
}
GENERATED_MARKERS = ("@generated", "auto-generated", "autogenerated", "generated by")
CONFIG_EXTENSIONS = {".json", ".toml", ".ini", ".cfg", ".properties", ".env"}
DOC_EXTENSIONS = {".md", ".rst", ".txt", ".adoc"}
SCHEMA_EXTENSIONS = {".sql", ".graphql", ".proto", ".avsc"}
DEPLOYMENT_NAMES = {"dockerfile", "docker-compose.yml", "helmfile.yaml", "kustomization.yaml"}
CI_DIR_PARTS = {".github", ".gitlab", ".circleci"}


class FileClassifier:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def should_index(self, path: Path, root: Path) -> bool:
        rel = path.relative_to(root)
        parts = {part.lower() for part in rel.parts}
        if parts & VENDOR_DIRS:
            return False
        if path.stat().st_size > self.settings.max_file_bytes:
            return False
        return self.classify(path, root) not in {
            FileClass.BINARY,
            FileClass.VENDOR,
            FileClass.GENERATED,
            FileClass.LARGE_UNKNOWN,
            FileClass.UNKNOWN,
        }

    def classify(self, path: Path, root: Path) -> FileClass:
        rel = path.relative_to(root)
        lower_parts = [part.lower() for part in rel.parts]
        lower_name = path.name.lower()
        suffix = path.suffix.lower()
        if any(part in VENDOR_DIRS for part in lower_parts):
            return FileClass.VENDOR
        if path.stat().st_size > self.settings.max_file_bytes:
            return FileClass.LARGE_UNKNOWN
        if self._is_binary(path):
            return FileClass.BINARY
        if self._looks_generated(path):
            return FileClass.GENERATED
        if any(part in CI_DIR_PARTS for part in lower_parts) or lower_name == ".gitlab-ci.yml":
            return FileClass.CI_CD
        if lower_name in DEPLOYMENT_NAMES or "deploy" in lower_parts or "helm" in lower_parts:
            return FileClass.DEPLOYMENT
        if "migration" in lower_parts or "migrations" in lower_parts:
            return FileClass.MIGRATION
        if suffix in SCHEMA_EXTENSIONS:
            return FileClass.SCHEMA
        if suffix in DOC_EXTENSIONS:
            return FileClass.DOCUMENTATION
        if suffix in CONFIG_EXTENSIONS or suffix in {".yml", ".yaml", ".xml"}:
            return FileClass.CONFIG
        if self._is_test_path(rel):
            return FileClass.TEST
        if suffix in self.settings.source_extensions:
            return FileClass.SOURCE
        return FileClass.UNKNOWN if path_language(path) == "text" else FileClass.CONFIG

    def _is_binary(self, path: Path) -> bool:
        try:
            sample = path.read_bytes()[:4096]
        except OSError:
            return True
        return b"\0" in sample

    def _looks_generated(self, path: Path) -> bool:
        try:
            head = path.read_text(encoding="utf-8", errors="ignore")[:2048].lower()
        except OSError:
            return False
        return any(marker in head for marker in GENERATED_MARKERS)

    def _is_test_path(self, path: Path) -> bool:
        parts = [part.lower() for part in path.parts]
        name = path.name.lower()
        return (
            "test" in parts
            or "tests" in parts
            or name.startswith("test_")
            or name.endswith("_test.py")
            or name.endswith(".test.ts")
            or name.endswith(".spec.ts")
            or name.endswith("test.java")
        )

